name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Deployment Scripts via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_DIR: "/srv/sistemkeuangankeluarga"
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          envs: APP_DIR
          script: |
            cd $APP_DIR

            # Tarik kode terbaru dari GitHub
            git pull origin main

            # Copy docker config dari folder docker/ ke root project
            cp docker/docker-compose.yml docker-compose.yml
            cp docker/Dockerfile Dockerfile

            # Matikan dan bangun ulang docker sesuai kode terbaru
            docker compose down
            docker compose up -d --build

            # Jalankan migrasi database otomatis jika ada tabel baru
            docker exec skk_app php artisan migrate --force

            # Optimasi cache framework laravel
            docker exec skk_app php artisan optimize:clear
            docker exec skk_app php artisan view:cache
            docker exec skk_app php artisan config:cache

            echo "Deployment Selesai!"
